name: 张玉洁的组件15-是否区分大小写
description: 描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十
keywords:
  - network
  - websocket
  - Network

license: aaa                                  # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

logo: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1565800191910&di=0c305258d202ea4a7d9e88bfbc733902&imgtype=0&src=http%3A%2F%2Fwww.cntv.cn%2Fprogram%2Fdhc%2F20040819%2Fimages%2F102216_013d.jpg

source_file:
  - src/*.c

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
